drop table if exists `autorizacion`;
drop table if exists `empleado`;
drop table if exists `configuracion`;
drop table if exists `tipo_configuracion`;
drop table if exists `token_blacklist`;
drop table if exists `rel_rol_permiso`;
drop table if exists `permiso`;
drop table if exists `seccion_permiso`;
drop table if exists `rol`;
create table `rol` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(50) not null, `created_by` int unsigned null, `updated_by` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `seccion_permiso` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(50) not null, `created_by` int unsigned null, `updated_by` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `permiso` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(80) not null, `descripcion` varchar(100) not null, `seccion_id` int unsigned not null, `created_by` int unsigned null, `updated_by` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `permiso` add constraint `permiso_seccion_id_foreign` foreign key (`seccion_id`) references `seccion_permiso` (`id`);
create table `rel_rol_permiso` (`id` int unsigned not null auto_increment primary key, `rol_id` int unsigned not null, `permiso_id` int unsigned not null, `created_by` int unsigned null, `updated_by` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `rel_rol_permiso` add constraint `rel_rol_permiso_rol_id_foreign` foreign key (`rol_id`) references `rol` (`id`);
alter table `rel_rol_permiso` add constraint `rel_rol_permiso_permiso_id_foreign` foreign key (`permiso_id`) references `permiso` (`id`);
create table `token_blacklist` (`id` int unsigned not null auto_increment primary key, `token` varchar(25) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `tipo_configuracion` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(50) not null, `created_by` int unsigned null, `updated_by` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `configuracion` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(50) not null, `descripcion` varchar(250) not null, `tipo_configuracion_id` int unsigned not null, `valor` varchar(200) not null, `created_by` int unsigned null, `updated_by` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `configuracion` add constraint `configuracion_tipo_configuracion_id_foreign` foreign key (`tipo_configuracion_id`) references `tipo_configuracion` (`id`);
create table `usuario` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(250) not null, `fecha_nacimiento` date not null, `email` varchar(255) not null, `genero` varchar(1) not null, `telefono` varchar(13) not null, `celular` varchar(13) not null, `fecha_ingreso` date not null, `rol_id` int unsigned null, `password` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `usuario` add constraint `usuario_rol_id_foreign` foreign key (`rol_id`) references `rol` (`id`);
alter table `usuario` add unique `usuario_email_unique`(`email`);
create table `autorizacion` (`id` int unsigned not null auto_increment primary key, `fecha` datetime not null, `usuario_id` int unsigned not null, `estatus` varchar(1) null, `comentario` varchar(150) null, `created_by` int unsigned null, `updated_by` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `autorizacion` add constraint `autorizacion_usuario_id_foreign` foreign key (`usuario_id`) references `usuario` (`id`);
create table `departamento` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(255) not null, `activo` tinyint(1) not null default '0', `created_by` int unsigned null, `updated_by` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `empresa` (`id` int unsigned not null auto_increment primary key, `nombre` varchar(255) not null, `activo` tinyint(1) not null default '0', `created_by` int unsigned null, `updated_by` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `rel_departamento_empresa` (`id` int unsigned not null auto_increment primary key, `empresa_id` int unsigned null, `departamento_id` int unsigned null, `usuario_id` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `rel_departamento_empresa` add constraint `rel_departamento_empresa_empresa_id_foreign` foreign key (`empresa_id`) references `empresa` (`id`);
alter table `rel_departamento_empresa` add constraint `rel_departamento_empresa_departamento_id_foreign` foreign key (`departamento_id`) references `departamento` (`id`);
alter table `rel_departamento_empresa` add constraint `rel_departamento_empresa_usuario_id_foreign` foreign key (`usuario_id`) references `usuario` (`id`);
